### PR TITLE
Keep pipeline consistent

### PR DESCRIPTION
**Pull request by liamrussell125**
The pipe is a list being passed through, my preference is to keep all operations on the pipeline to be of the initial data type.

Discuss.

### CODE REVIEW

**Comment by TWith2Sugars** [comment]
My reason for not that way is:

> When changing between list types, use the new type module to visually indicate this

**Comment by JohnHodkinson** [comment]
I also do not prefer this way for the same reason @TWith2Sugars mentioned above.

**Comment by TWith2Sugars** [comment]
Lets see if using the new github reactions can be used to "poll" this issue

**Comment by TWith2Sugars** [comment]
Been open long enough,

3-1 vote is good enough for me.

**Pull request closed without merging**
